### ISSUE TITLE
Using codes fot Slimefun items with number generates warnings

### ISSUE THREAD

**Issue by DrakstaarMSD** [WalshyDev/SFMobDrops#4]
### ❗ Checklist

- [X] I am using an up to date "DEV" (not "RC") version of SFMobDrops and Slimefun.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

The server throws this warning if use use Items such as MAGIC_LUMP_1  or GOLD_4K: [SFMobDrops] Slimefun ID should be in SCREAMING_SNAKE_CASE!
I haven't tested others yet.

### 📑 Reproduction Steps

Use this in the config.yml and restart the server

  - entity: WITCH
    slimefunItem: MAGIC_LUMP_1
    chance: 4.20

You will see the Warning in the Console

### 💡 Expected Behavior

The Item code should not have triggered a warning.

### 📜 Server Log

https://pastebin.com/MGEZLZqi

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.17.x

### ⭐ SFMobDrops and Slimefun version

SFMobDrops - DEV 1 (git 9f2e5)
Slimefun4 - DEV 942 (git 25dea)

**Comment by WalshyDev** [comment]
Fixed in build 2, thanks for reporting
