### ISSUE TITLE
RC-28 / RC-27

### ISSUE THREAD

**Issue by TheBusyBiscuit** [WalshyDev/SFMobDrops#5]
### ❗ Checklist

- [X] I am using an up to date "DEV" (not "RC") version of SFMobDrops and Slimefun.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

it was no updated.

### 📑 Reproduction Steps

update. it bork

### 💡 Expected Behavior

it fix, no bork!!!!!!!

### 📜 Server Log

lug

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ SFMobDrops and Slimefun version

lastest and fastest

### 🧭 Other plugins

Spooogot and SmileFun.

**Comment by WalshyDev** [comment]
Thanks for the very detailed report. This made finding the issue very easy and quick. I commend your excellent issue reporting. Build is released :)

**Comment by TheBusyBiscuit** [comment]
XD I am so sorry, buddy.
But I had to take the chance.
