### ISSUE TITLE
Multiple drops in config not registering to the same mob.

### ISSUE THREAD

**Issue by TheLittleCube** [WalshyDev/SFMobDrops#8]
### ❗ Checklist

- [X] I am using an up to date "DEV" (not "RC") version of SFMobDrops and Slimefun.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Boomer told me it would be best to let you know/ask what to do next. (How to fix if I was the one to mess it up.)

Config: https://pastebin.com/u690BewK
Testing: https://streamable.com/lhivxi

Each time I changed the drops I restarted the server to ensure that it was loading as I had intended. 
I started testing the addon in 1.18 and now am using it for 1.19.

End goal is to get [this](https://docs.google.com/spreadsheets/d/1RHDNx1K7eF8ysMtMYGF2W_qCXCF4REhyEUsTOuTWYKk/edit#gid=0) to be the new drops/rates for my players. As I spent the hours to get it to this point I wanted to make sure everything working. Before I wrote out the config. Cut to now..

Currently the addon only respects the first item in the config for that mob type.

Note: In the section for 'Minecraft version:" Unable to select anything past 1.17.X

### 📑 Reproduction Steps

Change config to desired drops/rates
Spawn/Kill selected entity to check drops. 

### 💡 Expected Behavior

Expected that each mob would roll the chances for multiple items attached to the configuration. 

### 📜 Server Log

https://pastebin.com/V3hyxBCM

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ SFMobDrops and Slimefun version

SFMobDrops - DEV 6
Slimefun 4 - DEV 1015

### 🧭 Other plugins

N/A

**Comment by TheLittleCube** [comment]
Update new [config](https://pastebin.com/h37Ed11b).

Because of my drop amounts. SFMobdrops now throws an error when using `/sfmobdrops list` as it can only display the first 54 drops. While I currently have 81 changes.

**Comment by WalshyDev** [comment]
Done in build 7 - https://blob.build/project/SFMobDrops
